### DISCUSSION TITLE
Zeitsynchronisation Home Assistant => Buderus Controller

### DISCUSSION THREAD

**Discussion by thoha1970** [the78mole/esphome_components#74] [Code Improvements]
Hallo zusammen,
ich setzte nun seit ein paar Wochen die KM271 Platine von Daniel ein und muss Euch mal ein ganz dickes Lob aussprechen.
Toll, was Ihr hier auf die Beine gestellt habt.

Ihr habt mit dem pull request #68 die Funktionalität eingebaut, dass man die RTC des Buderus Controller aktualisieren kann.
Hierzu muß man die Uhrzeit, Datum, ... über die jeweiligen entities in Home Assistant eingeben und dann an den Buderus Controller senden.

Ich habe diese Funktionalität in mein YAML file integriert und es funktioniert auch wunderbar.
Leider ist es ein bisschen mühselig, diese ganzen Zeit - Datum Einstellungen manuell vorzunehmen.

Ich habe mittlerweile Sensoren für Jahr, Monat, Tag des Monats, Tag der Woche, Stunden, Minuten und Sekunden mittels
        state: >-
          {{ now()._XXX_ }}
          
angelegt und diese funktionieren auch problemlos.
Diese Sensoren basieren auf der Systemzeit von Home Assistant, im Detail vom Home Assistant Host ( in meinem Fall ein RasPi5).
  
Wäre es denkbar, das YAML file so abzuändern, dass diese Daten nicht mehr über eine manuelle Eingabe eingegeben werden, sondern  auf den o.g. Sensoren basieren?

Das würde dann die Eingabe dieser Zeit / Datums Einstellungen ersetzten und sozusagen "automatisieren".

Den Wochentag könnte man ja bestimmt mittels einem Filter von "Tag der Woche" in "Wochentag" umwandeln.
Die Eingabe bzgl. Sommerzeit könnte ja weiterhin über ein Auswahlmenü erfolgen (ggf. kann man das auch noch über einen Filter automatisieren).

Best case noch eine entitiy anlegen, welche die Daten "live" anzeigt, damit man vor "senden" diese nochmal auf Korrektheit überprüfen kann.

Im nächsten Schritt könnten man dann noch eine Automatisierung erstellen, welche die entity "Datum und Zeit setzen" in einem festzulegenden Intervall aktiviert (z.B. 1x täglich um 24:00).

Danke für Eure Rückmeldung und ein schönes Wochenende

Thomas

**Comment by the78mole** [comment]
Hallo Thomas,

eigentlich sollte man das direkt in einer Lambda-Funktion abbilden können. Die Home-Assistant-Zeit kann man ganz easy mit ESPhome auf den ESP bringen, dafür ist nur ein Dreizeiler notwendig:

```yaml
time:
  - platform: homeassistant
    id: hasstime
```

In einem Sensor-Lambda kann ich mir diese Zeit dann auch recht einfach besorgen (hier ein Beispiel aus meinem WROVER-Display-Code für eine kleine Statusanzeige):

```yaml
display:
  - platform: ili9xxx
    # ....
    lambda: |-
      auto tt = id(hasstime).now();
      if(tt.second % 2 == 0 && tt.hour >= 5 && tt.hour <= 12) {
        if(tt.day_of_week == 2 || tt.day_of_week == 4 || tt.day_of_week == 6) {
          it.filled_rectangle(20, 150, 280, 30, my_red);
          it.printf(160, 165, id(ttf14), id(my_yellow), TextAlign::CENTER, "!!! Mo-Mi-Fr Action !!!");
        }
      }
      // ...
      it.strftime(320, 207, id(ttf14), id(my_yellow), TextAlign::BOTTOM_RIGHT, "%a %d.%m.%Y %H:%M", tt);
      // ...
```

`ttf14`, `my_red` und `my_yellow` muss man im Beispiel natürlich auch noch definieren, aber das ist ja für die Frage eher unwichtig.

Natürlich kannst Du genau so einen timer einrichten, dessen Lambda-Funktion dann den Wert bestimter Numbers setzt.

Hoffe, das hilft Dir weiter...

Kannst ja dann gerne mal einen Code posten, werde ihn gerne als snippet ins GitHub aufnehmen.

Grüße,
Daniel

**Reply by thoha1970** [reply]
Hallo Daniel,
ich habe mittlerweile mal auf meinem "Test ESP32" folgende Sensoren-Lambdas (wie von Dir beschrieben) erstellt und diese funktionieren auch wie erwartet:
aktuelles Jahr
aktueller Monat
aktueller Tag des Monats
aktueller Tag der Woche (id(hasstime).now().day_of_week -1, da es "iso_day_of_week" wohl nicht gibt)
aktuelle Stunden
aktuelle Minuten
aktuelle Sekunden

Wo ich noch meine Probleme habe:
aktueller Wochentag (Montag- Sonntag)
Sommerzeit ja / nein (aktuell bekomme ich nur 0 oder 1 zurück => Sommerzeit aktiv oder nicht aktiv)

Hast Du eine Idee, wie ich diese beiden Sensoren anlegen muß, damit ich die benötigten Daten bekomme?
Kennst Du eine Übersicht, wo die "members" von id(_HA platform time_).now() aufgeschlüsselt sind?

Wenn ich alle benötigten Sensoren auf meinem Test ESP32 mal am laufen habe, werde ich das ganze dann auf den KM271 adaptieren und das YAML file dementsprechend anpassen.

Grüße, Thomas

**Comment by thoha1970** [comment]
Hallo Daniel,

endlich, nach Monaten, bin ich dazugekommen, das aktualisieren der RTC des Buderus Controller in mein YAML file zu implementieren und zu testen.

Folgendes habe ich implementiert:

`time:
  - platform: homeassistant
    id: hasstime`
    
sensor:
   - platform: template
    name: "03_Jahr"
    id: year_to_set
    update_interval: 60s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().year;

  - platform: template
    name: "02_Monat"
    id: month_to_set
    update_interval: 60s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().month;

  - platform: template
    name: "01_Tag"
    id: day_to_set
    update_interval: 60s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().day_of_month;

  - platform: template
    name: "04_Stunden"
    id: hours_to_set
    update_interval: 10s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().hour;

  - platform: template
    name: "05_Minuten"
    id: minutes_to_set
    update_interval: 10s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().minute;

  - platform: template
    name: "06_Sekunden"
    id: seconds_to_set
    update_interval: 1s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().second;

  - platform: template
    name: "07_Wochentag"
    id: day_of_week_to_set
    update_interval: 1s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().day_of_week;

  - platform: template
    name: "08_DST Status"
    id: daylight_savings_time_to_set
    update_interval: 1s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().is_dst;

button:
  - platform: template
    name: "Datum und Zeit setzen"
    on_press:
      - lambda:
 
          uint16_t fullYear = id(year_to_set).state;
          uint8_t monthStartingAt0 = id(month_to_set).state -1;
          uint8_t dayOfMonthStartingAt1 = id(day_to_set).state;
          uint8_t weekDaySundayIs0 = id(day_of_week_to_set).state -1;
          uint8_t hours0To23 = id(hours_to_set).state;
          uint8_t minutes = id(minutes_to_set).state;
          uint8_t seconds = id(seconds_to_set).state;
          bool isDaylightSavingsTime = id(daylight_savings_time_to_set).state;

          budoil->set_heater_datetime(fullYear, monthStartingAt0, dayOfMonthStartingAt1,
                                      weekDaySundayIs0, hours0To23, minutes, seconds, isDaylightSavingsTime);
`

Zusätzlich habe ich folgende Automatisierung erstellt:

![image](https://github.com/user-attachments/assets/191cf161-a223-44eb-be81-39b528df4ad2)

Das ganze funktioniert auch ohne Probleme und ich werde die nächsten Tage beobachten, ob das alles dauerhaft und stabil funktioniert.

Falls alles stabil läuft, kannst Du diese Funktion ja (falls Du möchtest) übernehmen und implementieren.

Grüße und schöne Weihnachten

Thomas

**Reply by man55** [reply]
Hi. It's great that this works!
I'm trying to do this myself, but it's not working. I'm getting a config error.

Could you please post your code as CODE (like the78mole's example above) rather than as plain text?

And a couple of questions, if I may:
Am I correct in assuming I need to add all of this to my buderus.yaml file in ESPHome builder?
Should I use " - platform: template" since my buderus.yaml uses "-platform: km271_wifi" ?
TNX.

**Reply by thoha1970** [reply]
Hi,
attached my YAML file posted as code:

```
# This is a configuration with only heating circuit 1 and domestic
# hot water. You need to add your wifi credentials to make the esp
# join your home WiFi.
substitutions:
  name: "km271-for-friends"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: false

time:
  - platform: homeassistant
    id: hasstime

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: YOUR KEY

ota:
  platform: esphome
#  password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "KM271 Fallback Hotspot"
    password: ""

uart:
  id: uart_bus
  tx_pin: GPIO2
  rx_pin: GPIO4
  baud_rate: 2400

external_components:
  - source: github://the78mole/esphome_components@main
    components: [ km271_wifi ]
    refresh:    1sec

status_led:
  id: ledgn1
  pin:
    number: GPIO21
    inverted: true

km271_wifi:
  - id: budoil
    uart_id: uart_bus

binary_sensor:
  - platform: km271_wifi
    # Betriebswerte 1 HK1
    heating_circuit_1_switch_off_optimization:
      name: "HK1 Ausschaltoptimierung"
    heating_circuit_1_switch_on_optimization:
      name: "HK1 Einschaltoptimierung"
    heating_circuit_1_automatic:
      name: "HK1 Automatik"
    heating_circuit_1_ww_priority_processing:
      name: "HK1 Warmwasservorrang"
    heating_circuit_1_screed_drying:
      name: "HK1 Estrichtrocknung"
    heating_circuit_1_holiday:
      name: "HK1 Ferien"
    heating_circuit_1_antifreeze:
      name: "HK1 Frostschutz"
    heating_circuit_1_manually:
      name: "HK1 Manuell"
    # Betriebswerte 2 HK1
    heating_circuit_1_summer:
      name: "HK1 Sommer-Modus"
    heating_circuit_1_day:
      name: "HK1 Tag-Modus"
    heating_circuit_1_no_comm_with_rc:
      name: "HK1 Keine Kommunikation mit FB"
    heating_circuit_1_rc_faulty:
      name: "HK1 FB fehlerhaft"
    heating_circuit_1_flow_sensor_error:
      name: "HK1 Fehler Vorlauffuehler"
    heating_circuit_1_max_flow:
      name: "HK1 Maximaler Vorlauf"
    heating_circuit_1_external_fault_input:
      name: "HK1 Externer Stoereingang"
    # Betriebswerte 1 WW
    ww_automatic:
      name: "WW Automatik"
    ww_disinfection:
      name: "WW Desinfektion"
    ww_reload:
      name: "WW Nachladung"
    ww_holiday:
      name: "WW Ferien"
    ww_error_disinfection:
      name: "WW Fehler Desinfektion"
    ww_error_sensor:
      name: "WW Fehler Fuehler"
    ww_error_stays_cold:
      name: "WW Fehler WW bleibt kalt"
    ww_error_anode:
      name: "WW Fehler Anode"
    # Betriebswerte 2 WW
    ww_loading:
      name: "WW Laden"
    ww_manually:
      name: "WW Manuell"
    ww_reloading:
      name: "WW Nachladen"
    ww_switch_off_optimization:
      name: "WW Ausschaltoptimierung"
    ww_switch_on_optimization:
      name: "WW Einschaltoptimierung"
    ww_day_mode:
      name: "WW Tag Modus"
    ww_post_processing:
      name: "WW Nachbereitung"
    ww_priority_processing:
      name: "WW Vorrangschaltung"
    # Kesselfehler
    error_burner_malfunction:
      name: "Fehler Brennerstoerung"
    error_boiler_sensor:
      name: "Fehler Kesselfuehler"
    error_additional_sensor:
      name: "Fehler Zusatzfuehler"
    error_boiler_stays_cold:
      name: "Fehler Kessel bleibt kalt"
    error_exhaust_gas_sensor:
      name: "Fehler Abgasfuehler"
    error_exhaust_gas_over_limit:
      name: "Fehler Abgas ueber Grenzwert"
    error_safety_chain_released:
      name: "Fehler Sicherungskette ausgeloest"
    error_external_disturbance:
      name: "Fehler Externe Stoerung"
    # Kesselbetrieb
    boiler_emission_test:
      name: "Kessel Abgastest"
    boiler_1st_stage_operation:
      name: "Kessel Betrieb 1.Stufe"
    boiler_protection:
      name: "Kessel Schutz"
    boiler_under_operation:
      name: "Kessel unter Betrieb"
    boiler_actuation:
      name: "Brenneransteuerung"
  #Alarmstatus
    alarm_exhaust_gas_sensor:
      name: "Alarm Abgasfuehler"
    alarm_boiler_flow_sensor:
      name: "Alarm Kesselvorlauffuehler"
    alarm_burner:
      name: "Alarm Brenner"
    alarm_heating_circuit_2_flow_sensor:
      name: "Alarm HK2 Vorlauffuehler"
  #Other stuff
    load_pump_running:
      name: "Ladepumpenbetrieb"
    circulation_pump_running:
      name: "Zirkulationspumpenbetrieb"
    solar_pump_lowering:
      name: "Solarpumpe Absenkung"



output:
  - platform: gpio
    id: led3
    #name: LED3_Yellow
    pin:
      number: 23
      mode: OUTPUT
      inverted: true
  - platform: gpio
    id: led4
    #name: LED4_Red
    pin:
      number: 25
      mode: OUTPUT
      inverted: true

button:
  - platform: restart
    name: "KM271-WiFi Restart"

  - platform: template
    name: "Datum und Zeit setzen"
    on_press:
      - lambda:
 
          uint16_t fullYear = id(year_to_set).state;
          uint8_t monthStartingAt0 = id(month_to_set).state -1;
          uint8_t dayOfMonthStartingAt1 = id(day_to_set).state;
          uint8_t weekDaySundayIs0 = id(day_of_week_to_set).state -1;
          uint8_t hours0To23 = id(hours_to_set).state;
          uint8_t minutes = id(minutes_to_set).state;
          uint8_t seconds = id(seconds_to_set).state;
          bool isDaylightSavingsTime = id(daylight_savings_time_to_set).state;

          budoil->set_heater_datetime(fullYear, monthStartingAt0, dayOfMonthStartingAt1,
                                      weekDaySundayIs0, hours0To23, minutes, seconds, isDaylightSavingsTime);

number:
  - platform: km271_wifi
    config_ww_temperature:
      name: "Warmwassersolltemperatur Tag"
      mode: slider
    config_frost_switch_temperature:
      name: "Frost Umschalttemperatur"
      mode: slider

    config_heating_circuit_1_room_target_temperature_night:
      name: "Heizkreis 1 Raumsolltemperatur Nacht"
      mode: slider
    config_heating_circuit_1_room_target_temperature_day:
      name: "Heizkreis 1 Raumsolltemperatur Tag"
      mode: slider
    config_heating_circuit_1_holiday_target_temperature:
      name: "Urlaubstemperatur"
      mode: slider
    config_heating_circuit_1_flow_temperature_max:
      name: "Heizkreis 1 Heizkreistemperatur Maximal"
      mode: slider
    config_heating_circuit_1_design_temperature:
      name: "Heizkreis 1 Auslegungstemperatur"
      mode: slider
    config_heating_circuit_1_room_temperature_offset:
      name: "Heizkreis 1 Raumtemperatur Offset"
      mode: slider
    config_heating_circuit_1_holiday_days:
      name: "Heizkreis 1 Urlaubstage"
      mode: slider


select:
  - platform: km271_wifi
    config_ww_operation_mode:
      name: "Warmwasser Betriebsmodus"
    config_ww_circular_pump_interval:
      name: "Warmwasser Zirkulationspumpenintervall"
    config_heating_circuit_1_summer_winter_switch_temperature:
      name: "Heizkreis 1 Sommer Winter Umschalttemperatur"
    config_heating_circuit_1_operation_mode:
      name: "Heizkreis 1 Betriebsmodus"
    config_heating_circuit_1_lowering_type:
      name: "Heizkreis 1 Absenkungsart"
    config_heating_circuit_1_heating_system_type:
      name: "Heizkreis 1 Heizsystem"
    config_heating_circuit_1_heating_program:
      name: "Heizkreis 1 Heizprogramm"


sensor:
  - platform: km271_wifi
    heating_circuit_1_flow_target_temperature:
      name: "HK1 Vorlaufsolltemperatur"
    heating_circuit_1_flow_temperature:
      name: "HK1 Vorlaufisttemperatur"
    heating_circuit_1_room_target_temperature:
      name: "HK1 Raumsolltemperatur"
    heating_circuit_1_room_temperature:
      name: "HK1 Raumisttemperatur"
    heating_circuit_1_pump_power:
      name: "HK1 Pumpenleistung"
    heating_circuit_1_mixer_position:
      name: "HK1 Mischerstellung"
    heating_circuit_1_curve_p10:
      name: "HK1 Heizkurve +10 °C"
    heating_circuit_1_curve_0:
      name: "HK1 Heizkurve 0 °C"
    heating_circuit_1_curve_n10:
      name: "HK1 Heizkurve -10 °C"
    ww_target_temperature:
      name: "Warmwassersolltemperatur"
    ww_temperature:
      name: "Warmwasseristtemperatur"
    boiler_target_temperature:
      name: "Kesselvorlaufsolltemperatur"
    boiler_temperature:
      name: "Kesselvorlaufisttemperatur"
    boiler_turn_on_temperature:
      name: "Brennereinschalttemperatur"
    boiler_turn_off_temperature:
      name: "Brennerausschalttemperatur"
    exhaust_gas_temperature:
      name: "Abgastemperatur"
    outdoor_temperature:
      name: "Aussentemperatur"
    attenuated_outdoor_temperature:
      name: "Gedaempfte Aussentemperatur"
# Brennerlaufzeit in Minuten
    boiler_runtime_1:
      name: "Brennerlaufzeit 1"
      id: boiler_runtime_1
    boiler_runtime_2:
      name: "Brennerlaufzeit 2"

# START Datum und Uhrzeit für Zeitsynchronisation von hasstime:

  - platform: template
    name: "03_Jahr"
    id: year_to_set
    update_interval: 60s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().year;

  - platform: template
    name: "02_Monat"
    id: month_to_set
    update_interval: 60s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().month;

  - platform: template
    name: "01_Tag"
    id: day_to_set
    update_interval: 60s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().day_of_month;

  - platform: template
    name: "04_Stunden"
    id: hours_to_set
    update_interval: 10s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().hour;

  - platform: template
    name: "05_Minuten"
    id: minutes_to_set
    update_interval: 10s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().minute;

  - platform: template
    name: "06_Sekunden"
    id: seconds_to_set
    update_interval: 1s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().second;

  - platform: template
    name: "07_Wochentag"
    id: day_of_week_to_set
    update_interval: 1s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().day_of_week;

  - platform: template
    name: "08_DST Status"
    id: daylight_savings_time_to_set
    update_interval: 1s
    accuracy_decimals: 0
    lambda: |- 
       return id(hasstime).now().is_dst;

# ENDE Datum und Uhrzeit für Zeitsynchronisation von hasstime: 

  - platform: wifi_signal
    name: "KM217 WiFi Signal Sensor"
    update_interval: 60s

  - platform: adc
    pin: 36
    unit_of_measurement: "V"
    name: "KM217 5V Supply"
    accuracy_decimals: 2
    update_interval: 5s
    attenuation: 6dB
    filters:
      - multiply: 3.0955414
      - throttle_average: 60s

  - platform: template
    name: "Ölverbrauch Brenner in kWh"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    entity_category: diagnostic
    accuracy_decimals: 3
#  Berechnung auf Basis Betriebszeit Brenner in Minuten x (Nennleistung Brenner in kW / Korrekturfaktor, um auf 2,23L/h zu kommen) / 60 (Umrechnung kW/min in kW/h)
    lambda: |-    
      if(id(boiler_runtime_1).state) {
        return id(boiler_runtime_1).state * (21.0 / 0.9417) / 60.0;
      } 
      return NAN;

#  Berechnung auf Basis Betriebszeit Brenner in Minuten x (Nennleistung Brenner in kW / Korrekturfaktor, um auf 2,23L/h zu kommen) / 60 (Umrechnung L/min in L/h)
  - platform: copy
    name: "Ölverbrauch Brenner in Liter"
    unit_of_measurement: L
    device_class: volume
    state_class: total_increasing
    entity_category: diagnostic
    accuracy_decimals: 1
    source_id: boiler_runtime_1
           
    filters:
      - lambda: return id(boiler_runtime_1).state * (2.10 / 0.9417) / 60.0;
 
switch:
  - platform: gpio
    name: LED2_Green
    pin:
      number: 22
      mode: OUTPUT
      inverted: true

text_sensor:
  - platform: km271_wifi
    firmware_version:
      name: "Firmwareversion Steuerung"


  - platform: wifi_info
    ip_address:
      name: IP Address (DHCP)




```
