### ISSUE TITLE
Warmwassersolltemperatur wird falsch angezeigt

### ISSUE THREAD

**Issue by arnkit** [the78mole/esphome_components#35]
Hallo ihr beiden,

erstmal - ihr macht echt super Arbeit. Geniale Einbindung in ESPHome und Homeassistant.

Mit dem Update von gestern scheint sich jedoch ein Fehler eingeschlichen zu haben. Bei mir wird die Warmwassersolltemperatur (WWST) jetzt mit 10 Grad angezeigt, davor waren er 50 (richtiger Wert). Ich habe versucht den Code nachzuvollziehen, konnte aber keine Fehler oder Veränderungen feststellen. Die Warmwasseristtemperatur ist nach wie vor richtig.

![image](https://user-images.githubusercontent.com/46427959/208072944-95c09970-73c2-4d86-b12e-0fc8b0ed1686.png)

Zusätzlich ist mir in der _buderus-km271.yaml_ aufgefallen, dass beider Werte WWSoll und WWIst wie folgt angegeben sind
```
    hot_water_target_temperature:  
      name: "Warmwassersolltemperatur"
    hot_water_temperature:
      name: "Warmwasseristtemperatur"
```

hot_water_xxx gibts jedoch nicht mehr, ich vermutze es müsste ww_xxx heißen.
```
    ww_target_temperature:
      name: "Warmwassersolltemperatur"
    ww_temperature:
      name: "Warmwasseristtemperatur"
```

Viele Grüße arne
