### ISSUE TITLE
Expand writer queue

### ISSUE THREAD

**Issue by jensgraef** [the78mole/esphome_components#7]
Currently the writer class only supports one telegram at a time.
This should be changed to allow multiple pending write commands.

See https://github.com/the78mole/esphome_components/issues/4#issuecomment-1336187716 for the original suggestion.

**Comment by jensgraef** [comment]
I just pushed the first attempt at implementing a writer queue to https://github.com/the78mole/esphome_components/tree/larger-write-queue
It compiles but I have not yet tested it it.

Cases to test:
- Adding a single telegram to the writer (no usage of the queue)
- adding two telegrams to the writer (single usage of the queue)
- adding three telegrams to the writer (dual usage of the queue - offset calculation check)
- filling the queue

**Comment by Bascht74** [comment]
I testet the new tree with my config and it works at least in normal environments. 

I am using this configuration right now: 

```
select:
  - platform: template
    name: "Warmwasser Betriebsart"
    id: warmwasser_betriebsart
    entity_category: config
    optimistic: true
    options:
      - Dauerhaft aus (0)
      - Dauerhaft ein (1)
      - Automatik (2)
    initial_option: Automatik (2)
    set_action: 
      - lambda:
          auto index = id(warmwasser_betriebsart).index_of(x);
          if (index.has_value()) {
            uint8_t command[] = {0x0C, 0x0E, (uint8_t)index.value(), 0x65, 0x65, 0x65, 0x65, 0x65};
            budoil->writer.enqueueTelegram(command, 8);
          }
  - platform: template
    name: "Heizung Betriebsart"
    id: heizung_betriebsart
    entity_category: config
    optimistic: true
    options:
      - manuell Nacht (0)
      - manuell Tag (1)
      - Automatik (2)
    initial_option: Automatik (2)
    set_action: 
      - lambda:
          auto index = id(warmwasser_betriebsart).index_of(x);
          if (index.has_value()) {
            uint8_t command[] = {0x07, 0x00, 0x65, 0x65, 0x65, 0x65, (uint8_t)index.value(), 0x65};
            budoil->writer.enqueueTelegram(command, 8);
          }
  - platform: template
    name: "Warmwasser Zirkulation"
    id: warmwasser_zirkulation
    entity_category: config
    optimistic: true
    options:
      - dauerhaft aus
      - 1x pro Stunde
      - 2x pro Stunde
      - 3x pro Stunde
      - 4x pro Stunde
      - 5x pro Stunde
      - 6x pro Stunde
      - dauerhaft an
    initial_option: 1x pro Stunde
    set_action: 
      - lambda:
          auto index = id(warmwasser_betriebsart).index_of(x);
          if (index.has_value()) {
            uint8_t command[] = {0x0C, 0x0E, 0x65, 0x65, 0x65, 0x65, 0x65, (uint8_t)index.value()};
            budoil->writer.enqueueTelegram(command, 8);
          }
  - platform: template
    name: "Sommer ab"
    id: sommer_ab
    entity_category: config
    optimistic: true
    options:
      - Sommer
      - 10 °C
      - 11 °C
      - 12 °C
      - 13 °C
      - 14 °C
      - 15 °C
      - 16 °C
      - 17 °C
      - 18 °C
      - 19 °C
      - 20 °C
      - 21 °C
      - 22 °C
      - 23 °C
      - 24 °C
      - 25 °C
      - 26 °C
      - 27 °C
      - 28 °C
      - 29 °C
      - 30 °C
      - Winter
    initial_option: 18 °C
    set_action: 
      - lambda:
          auto index = id(warmwasser_betriebsart).index_of(x);
          if (index.has_value()) {
            uint8_t command[] = {0x07, 0x00, 0x65, (uint8_t)index.value(), 0x65, 0x65, 0x65, 0x65};
            budoil->writer.enqueueTelegram(command, 8);
          }
```

**Comment by jensgraef** [comment]
Merged and solved with #10

**Comment by Bascht74** [comment]
> Cases to test:
> 
> * Adding a single telegram to the writer (no usage of the queue)
> * adding two telegrams to the writer (single usage of the queue)
> * adding three telegrams to the writer (dual usage of the queue - offset calculation check)
> * filling the queue

Can i help with that?

> * Adding a single telegram to the writer (no usage of the queue) 
--> Works, as I am using this right now.

> * adding two telegrams to the writer (single usage of the queue)
--> I could easily add to commands to my select, e.g. 
```
      - lambda:
          auto index = id(warmwasser_betriebsart).index_of(x);
          if (index.has_value()) {
            uint8_t command[] = {0x07, 0x00, 0x65, 0, 0x65, 0x65, 0x65, 0x65};
            budoil->writer.enqueueTelegram(command, 8);
            uint8_t command[] = {0x07, 0x00, 0x65, (uint8_t)index.value(), 0x65, 0x65, 0x65, 0x65};
            budoil->writer.enqueueTelegram(command, 8);
```


> * adding three telegrams to the writer (dual usage of the queue - offset calculation check)
--> I could easily add to commands to my select, e.g. 
```
      - lambda:
          auto index = id(warmwasser_betriebsart).index_of(x);
          if (index.has_value()) {
            uint8_t command[] = {0x07, 0x00, 0x65, 0, 0x65, 0x65, 0x65, 0x65};
            budoil->writer.enqueueTelegram(command, 8);
            uint8_t command[] = {0x07, 0x00, 0x65, 1, 0x65, 0x65, 0x65, 0x65};
            budoil->writer.enqueueTelegram(command, 8);
            uint8_t command[] = {0x07, 0x00, 0x65, (uint8_t)index.value(), 0x65, 0x65, 0x65, 0x65};
            budoil->writer.enqueueTelegram(command, 8);
```
> * filling the queue
--> What does this mean? e.g. add ten, twenty entries to the queue?

... how to check that the result is OK?
Just check the the queue is sent to buderus and we get an ACK?

**Comment by jensgraef** [comment]
Yeah, we wrote at the same time. I've added some tests for it, @the78mole tested it on his setup and if it doesn't cause any problems at your installation, I'm happy  :)

**Comment by Bascht74** [comment]
No problems, 

I found a little copy paste error within my lambda, but that was my fault. 
Works as expected, but I didn't try to add lot's of entries to the queue. Just "normal" chances of values...

**Comment by the78mole** [comment]
I didn't test all options, but at least it still compiles and works with my config. You both are crazy 🤣 I love it 🥰

But I'll extend my config during the upcoming days. Just need some time for that.

**Comment by Bascht74** [comment]
Yes, baby. 
Genau das, was ich wollte 👍 
exactly what I wanted to achieve ... :-)

```
time:
  - platform: sntp
    id: sntp_time
    on_time:
      # Immer morgens um 08:00 Uhr 15 Minuten Wasser Zirkulation laufen lassen...
      - seconds: 0
        minutes: 0
        hours: 8
        days_of_week: MON-SUN
        then:
          - text_sensor.template.publish:
              id: logging
              state: "Schalte Warmwasserzirkulation für 15 Minuten ein"
          - select.set_index:
              id: warmwasser_zirkulation
              index: 7 # Dauerhaft an
          - delay: 15min # 15 Minuten warten
          - select.set_index:
              id: warmwasser_zirkulation
              index: 0 # wieder Dauerhaft aus
      # Immer Mittwochs um 14:00 Uhr Wasser aufheizen auf 65 Grad für 2 Stunden ...
      - seconds: 0
        minutes: 0
        hours: 14
        days_of_week: WED
        then:
          - text_sensor.template.publish:
              id: logging
              state: "Thermische Desinfektion. Warmwasser für 2 Stunden auf 65 Grad stellen und Warmwasserbetrieb einschalten"
          - select.set_index:
              id: warmwasser_betriebsart
              index: 2 # WW Automatik (Berücksichtigt Heizung Sommer, Urlaub usw.
          - number.set: 
              id: warmwasser_Temperatur
              value: 65 # Grad
          - delay: 2h # 2 Stunden warten
          - text_sensor.template.publish:
              id: logging
              state: "Thermische Desinfektion beendet. Warmwasser wieder auf 50 Grad stellen und Warmwasserbetrieb wieder ausschalten"
          - number.set: 
              id: warmwasser_Temperatur
              value: 50 # Grad
          - select.set_index:
              id: warmwasser_betriebsart
              index: 0 # WW Nachtmodus / Dauerhaft aus
      # Immer jeden Tag außer Mittwochs um 14:00 Uhr Wasser aufheizen auf 50 Grad für 1 Stunde ...
      - seconds: 0
        minutes: 0
        hours: 14
        days_of_week: MON,TUE,THU,FRI,SAT,SUN
        then:
          - text_sensor.template.publish:
              id: logging
              state: "Warmwasserbetrieb für 1 Stunde einschalten"
          - select.set_index:
              id: warmwasser_betriebsart
              index: 2 # WW Automatik (Berücksichtigt Heizung Sommer, Urlaub usw.
          - delay: 1h # 1 Stunden warten
          - text_sensor.template.publish:
              id: logging
              state: "Warmwasserbetrieb wieder ausschalten"
          - select.set_index:
              id: warmwasser_betriebsart
              index: 0 # WW Nachtmodus / Dauerhaft aus

```

Kleine Nebenstory:

Ich habe übrigens das mit dem defekten Sensor herausbekommen, was da los ist. 
Der Heizungsbauer hat den einfach nur "lose" in den Warmwasser-Tank reingeschoben. 
D.h. der lag überhaupt nicht an der wand an und hat daher nur eine "Vermutung" über die Warmwassertemperatur gehabt. 
Dadurch hat er immer eine zu niedrige Temperatur angezeigt.

Somit hat die Heizung bei zuvor eingestellten 60 Grad immer schön 80° Heizungswasser reingeschoben, bis dann im Messbereich auf 65 Grad "Lufttemperatur" vorhanden waren. Das läuft jetzt schon seit 8 Jahren so, seitdem der WW-Speicher ausgetauscht wurde. Die Verrohrung zwischen Heizung und WW-Speicher waren zudem nur unzureichend gedämmt. Im Kellerraum waren es 22 Grad bei offenem Fenster. Keine Ahnung, was das an Gas über die 8 Jahre gekostet haben dürfte....
Heute kam der Heizungsbauer und hat sich das angesehen und Buderus die "Schuld" gegeben. Er hatte es aber m.E. nicht so eingebaut, wie es in der Anleitung vorhanden war und das Ergebnis "kann so nicht gut funktionieren" einfach "ignoriert". 
Jetzt wird er ausgetauscht und das ganze ordentlich gemacht...
Zusätzlich machen wir jetzt nur 1x pro Tag WW (50°) und 1x am Tag Zirkulation zum Spülen und 1x pro Woche Desinfektion (dafür jetzt 65 Grad). Bin gespannt, wie sich das Auswirkt. Habe Thermometer im Keller (in HA integriert) und ESPHome am Gaszähler laufen :-). 

Will jetzt noch einen Wärmemengenzähler installieren lassen, damit man sehen kann, wie effizient die Heizung noch läuft und ob eine WP (ggf. als Zusatz) geht.
In einem anderen Haus habe ich das schon so laufen. Das ist noch ein Konstanttemperaturkessel installiert. Der braucht immer zwischen 60-70 Grad und hatte <  45% Effizienz Den haben wir jetzt schön mit 10cm Dämmung hinten, 6cm vorne und rundum auch nochmal 3cm eingepackt und schon ist die Effizient auf 75% hochgegangen (Raumtemperatur auch von 20,5 Grad auf 16 Grad gesunken im Keller). Viel Heizung und Heizrohre im Keller dämmen hilft scheinbar schon eine Menge. Flir sei Dank, kann man den Erfolg sogar sehen und wo noch Handlungsbedarf ist...
