### ISSUE TITLE
HK2 Raumtemperatur Offset shows 124,5 after ESPHome update

### ISSUE THREAD

**Issue by EPGK** [the78mole/esphome_components#75]
Hi!
After updating ESPHome the Offset of HK2 Raumtemperatur shows 124,5 instead off -4.
As far as I can tell, it's not changing anything. Just reading the value wrong.
![Screenshot 2024-06-05 142431](https://github.com/the78mole/esphome_components/assets/167763063/8c6abc9f-aca9-4b71-9ac8-289cf025524d)
![Screenshot 2024-06-05 143321](https://github.com/the78mole/esphome_components/assets/167763063/874db523-893a-45ea-91c3-4c2a7934bcd2)

**Comment by the78mole** [comment]
To be honest, I don't understand, why you experience this issue. I can not find any evidence, that this parameter has changed in the code and it still looks very similar to the HK1 offset. Unfortunately, I have no HK2 installed and therefore, no experience with it. Do you see similar problems also with HK1?

**Comment by EPGK** [comment]
I just redid the ESPHome update with HK1 Offset -1 and it jumpted to plus 5
![Screenshot 2024-06-05 151914](https://github.com/the78mole/esphome_components/assets/167763063/64bba1fb-a5ec-45bd-93a0-e6e795233c8f)
The same seems to happen with HK2. Its 5 but shows 124,5
![Screenshot 2024-06-05 151800](https://github.com/the78mole/esphome_components/assets/167763063/bf7e84e9-0c50-463a-96af-a6a46f01af46)

**Comment by the78mole** [comment]
When I change my HK1 room temp offset to 2°C in the UI, I see the following LOG:
![image](https://github.com/the78mole/esphome_components/assets/7723396/9026fe84-48d9-4b6a-9c76-3709dc4c0c43)

Explained: 04h = 04d => 4 / 2 = 2.0

But the parameter itself has in fact not a 0.5°C accuracy and also on the Buderus itself, I can only change the value in steps of 1 °C. It is only represented by such parameter.

The code for HK1 tells the correct parameter and the correct interpretation:
```C
{config_heating_circuit_1_room_temperature_offset, CFG031, true, SensorType::BYTE_DIVIDED_BY_2_AT_OFFSET, 3, "CFG_HK1_Raumtemperatur Offset", "°C"}
```

The (new) part in my ESPhome config looks like the following, I have just added to dig into this problem:
```yaml
number:
  - platform: km271_wifi
    config_ww_temperature:
      name: "Warmwassersolltemperatur Tag"
      mode: slider
    config_heating_circuit_1_design_temperature:
      name: "Auslegungstemperatur"
      mode: slider
    config_heating_circuit_1_room_target_temperature_day:
      name: "HK1 Raumsolltemperatur Tag"
    config_heating_circuit_1_room_temperature_offset:
      name: "HK1 Room Temp Offset"
```

Could you please check, if everything aligns with my stuff and add the Log output of the ESP (like in my first image), where the raw values of the received params are printed? 

Regards,
Daniel
