### ISSUE TITLE
Process a single bit of a telegram for a sensor.

### ISSUE THREAD

**Issue by jensgraef** [the78mole/esphome_components#9]
Be able to process a single bit of a byte of a specific telegram and use that for a sensor -> read "Betriebswerte" of HK1, WW and so on.

See https://github.com/the78mole/esphome_components/issues/4#issuecomment-1336187716 for the original suggestion.

**Comment by Bascht74** [comment]
@jensgraef We need that e.g. for this: 

`        { LPWW      , true, false, SensorType::INT, 0, "Ladepumpe", "", NULL },                          // ["aus", "Ladepumpe", "Warmwasserpumpe", "beide"]`

There we need to create two binary sensors out of it: 
```
BIN 00 DEC 0 = Beide aus
BIN 01 DEC 1 = Ladepumpe an
BIN 10 DEC 2 = Zirkulationspumpe an
DIN 11 DEC 3 = Ladepumpe und Zirkulationspumpe an
```
actually this telegram is mapped to a binary sensor so only the first bit is processed (Ladepumpe an/aus).

Do you see any way to do that with the existing code?

This is the water heater of the Buderus: 
![image](https://user-images.githubusercontent.com/66269310/206517341-8b7c744a-1847-4de1-85d1-c8c99415e690.png)

As you can see there must be something wrong with it because it is losing temperature quiet fast... 15°C in 2,6 hours !?!?
That is why I want so see the circulation that is behind the other "bit" --> Zirkulationspumpe :-) ...

**Comment by jensgraef** [comment]
With the current code you could map it to a numeric sensor and do the remaining work in home assistant, e.g. with an automation that toggles two switches depending on the value of the number.

I've got a rough idea how to do it in the km217 module, but it's not yet full thought true:
1. create a new sensor type BitArray
2. create a new class for  handling those bit arrays. This class should carry a list map of bit indices to binary sensors
3. extend the python part to allow telling the module "this is a binary sensor, and it should watch bit x of this parameter
4. extend the main class to add such a binary sensor to the class defined in 2

I wont have much time until next week, so it might take some time to build this.

**Comment by the78mole** [comment]
@jensgraef you name it, it is really crap to implement inside an ESPhome component.

**Comment by Bascht74** [comment]
Yes, this is how modbus controller has done it. 

Maybe this could help (I don't understand it completely but it seems to follow a lot of @jensgraef points... )

https://esphome.io/components/modbus_controller.html
--> Section bitmask in the documentation

Code:
https://github.com/esphome/esphome/blob/dev/esphome/components/modbus_controller/modbus_controller.h
--> template<typename N> N mask_and_shift_by_rightbit(N data, uint32_t mask)
plus: 
https://github.com/esphome/esphome/tree/dev/esphome/components/modbus_controller/binary_sensor

Maybe we could do the same with the address and byte that has so be read?

So maybe something like this could be very flexibly, because everybody can "select" anything via his yaml code without changing the source / adding something to the source: 

```
binary_sensor:
- platform: km271_wifi
  id: some_sensor_id
  name: "Zirkulationspumpe"
  address: 0x8429
  byte: 1
  bitmask: 0x2 #bit 1
- platform: km271_wifi
  id: some_sensor_id
  name: "Ladepumpe"
  address: 0x8429
  byte: 1 # first byte after the address
  bitmask: 0x1 #bit 0
- platform: km271_wifi
  id: some_sensor_id
  name: "Absenkung_Solar"
  address: 0x8429
  byte: 1 # first byte after the address
  bitmask: 0x2 #bit 2
```

same "style" for sensors: 
```
- platform: km271_wifi
  id: raumsolltemperatur_hk1
  name: "Raumsolltemperatur HK1"
  address: 0x8004
  byte: 1 # first byte after the address
  unit_of_measurement: "°c"
  device_class: "temperature"
  state_class: "measurement"
  value_type: U_INT_DIV2
  accuracy_decimals: 1
```
This way we could even read the config variables to sensors: 
```
- platform: km271_wifi
  id: tagtemperatur_hk1
  name: "Tagtemperatur_HK1"
  address: 0x0000
  byte: 3 # third byte after the address
  unit_of_measurement: "°c"
  device_class: "temperature"
  state_class: "measurement"
  value_type: U_INT # unsigned integer
  accuracy_decimals: 1
```

It would be more generic and will need longer yaml code but you would be very flexible with the yaml without changing anything to the c++ code...
